### ISSUE TITLE
Logging stops after about 10 minutes

### ISSUE THREAD

**Issue by molly78** [yoctopuce/YoctoCloud#1]
Hello all.,

Running this on a pi3 with the latest updates on Rasbian Pixel. With the official Pi Touchscreen, and on Apache.

It seems that VirtualHub only responds for about 10-15 minutes, and then stops.

A graph is here:

<img width="804" alt="pi_graph" src="https://cloud.githubusercontent.com/assets/17839912/22008958/ed749408-dc3c-11e6-8bca-61d47f14e65a.PNG">

It's not until I hit the hub's page at :4444 that it starts sending data again... for another 10-15 minutes

I have already edited /etc/kbd/config and set powerdown_time=0
blank_time is set at 10

Any help would be appreciated :)

**Comment by molly78** [comment]
checked apache's error logs and found:

`[Mon Jan 16 20:34:31.414660 2017] [:error] [pid 1154] [client 127.0.0.1:36136] PHP Fatal error:  Uncaught exception 'YAPI_Exception' with message 'Network error while reading from device' in /var/www/html/yocto_api.php:4819\nStack trace:\n#0 /var/www/html/yocto_api.php(5196): YFunction->_throw(-3, 'Network error w...', -3)\n#1 /var/www/html/yocto_api.php(5467): YFunction->load(5)\n#2 /var/www/html/index.php(355): YSensor->get_currentValue()\n#3 /var/www/html/index.php(651): handleSensor(Object(YSensor), -1, -1)\n#4 {main}\n  thrown in /var/www/html/yocto_api.php on line 4819
[Mon Jan 16 20:35:04.951783 2017] [:error] [pid 715] [client 127.0.0.1:36148] PHP Fatal error:  Uncaught exception 'YAPI_Exception' with message 'Network error while reading from device' in /var/www/html/yocto_api.php:4819\nStack trace:\n#0 /var/www/html/yocto_api.php(5196): YFunction->_throw(-3, 'Network error w...', -3)\n#1 /var/www/html/yocto_api.php(5467): YFunction->load(5)\n#2 /var/www/html/index.php(355): YSensor->get_currentValue()\n#3 /var/www/html/index.php(651): handleSensor(Object(YSensor), -1, -1)\n#4 {main}\n  thrown in /var/www/html/yocto_api.php on line 4819
[Mon Jan 16 20:42:16.403671 2017] [:error] [pid 717] [client 127.0.0.1:36336] PHP Fatal error:  Uncaught exception 'YAPI_Exception' with message 'Network error while reading from device' in /var/www/html/yocto_api.php:4819\nStack trace:\n#0 /var/www/html/yocto_api.php(5196): YFunction->_throw(-3, 'Network error w...', -3)\n#1 /var/www/html/yocto_api.php(5467): YFunction->load(5)\n#2 /var/www/html/index.php(355): YSensor->get_currentValue()\n#3 /var/www/html/index.php(651): handleSensor(Object(YSensor), -1, -1)\n#4 {main}\n  thrown in /var/www/html/yocto_api.php on line 4819
[Mon Jan 16 20:44:52.631923 2017] [:error] [pid 717] [client 127.0.0.1:36396] PHP Fatal error:  Uncaught exception 'YAPI_Exception' with message 'invalid data:[\n{"/api.json":\r\n{\n"module":{"productName":"VirtualHub","serialNumber":"VIRTHUB0-","logicalName":"","productId":0,"productRelease":1,"firmwareRelease":"26144","persistentSettings":2,"luminosity":50,"beacon":0,"upTime":2860974714,"usbCurrent":0,"rebootCountdown":0,"userVar":0},\n"network":{"logicalName":"pi_logger","advertisedValue":"","readiness":3,"macAddress":"00:00:00:00:00:00","ipAddress":"0.0.0.0","subnetMask":"0.0.0.0","router":"0.0.0.0","ipConfig":"DHCP:169.254.0.0/16/169.254.0.1","primaryDNS":"0.0.0.0","secondaryDNS":"0.0.0.0","ntpServer":"0.0.0.0","userPassword":"","adminPassword":"","httpPort":4444,"defaultPage":"","discoverable":0,"wwwWatchdogDelay":0,"callbackUrl":"http://localhost/","callbackMethod":0,"callbackEncoding":4,"callbackCredentials":":","callbackInitialDelay":3,"callbackMinDelay":3,"callbackMaxDelay":600,"poeCurrent":0},\n"services":{\n"whitePages":[\n{"serialNumber":"VIRTHUB0-","logicalName":"","productName in /var/www/html/yocto_api.php on line 1480
`

**Comment by molly78** [comment]
Trying setting blank_time to 0 overnight & see what happens

Nope, but this time I got 30 minutes of logging before it stopped ?!

**Comment by yoctopuce** [comment]
Could you post the logs of the VirtualHub? 
If you have used the default startup script the logs they should be `/var/log/virtualhub.log`

**Comment by molly78** [comment]
Hmmm

.
[2017-01-15 17:26:37] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-15 17:26:37] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-15 17:26:37] (01) Unable to open settings file (/etc/vhub.byn), using default settings
[2017-01-15 17:26:37] (01) Save default settings
[2017-01-15 17:26:37] (01) NetworkName is pi_logger
[2017-01-15 17:26:37] (01) LogicalName is not set
[2017-01-15 17:26:37] (01) [1]ystream: 2198: Device THRMCPL1-807D7 plugged
[2017-01-15 17:26:37] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-15 17:26:37] (01) HTTP server is listening port 4444
[2017-01-15 17:26:37] (01) VXI-11 server is listening port 4445
[2017-01-15 17:32:09] (02) 00:32:09 Callback connected
[2017-01-15 17:32:17] (02) 00:32:17 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-15 17:46:45] (02) 00:46:45 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-15 17:47:14] (02) 00:47:14 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-15 17:52:10] (02) 00:52:10 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-15 17:52:44] (02) 00:52:44 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-15 17:54:50] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-15 17:54:50] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-15 17:54:50] (01) Save default settings
[2017-01-15 17:54:50] (01) NetworkName is pi_logger
[2017-01-15 17:54:50] (01) LogicalName is not set
[2017-01-15 17:54:50] (01) HTTP server is listening port 4444
[2017-01-15 17:54:50] (01) VXI-11 server is listening port 4445
[2017-01-15 17:55:01] (02) 00:55:01 Callback connected
[2017-01-15 18:16:12] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-15 18:16:12] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-15 18:16:12] (01) Save default settings
[2017-01-15 18:16:12] (01) NetworkName is pi_logger
[2017-01-15 18:16:12] (01) LogicalName is not set
[2017-01-15 18:16:12] (01) HTTP server is listening port 4444
[2017-01-15 18:16:12] (01) VXI-11 server is listening port 4445
[2017-01-15 18:16:20] (02) 01:16:20 Callback connected
[2017-01-15 18:19:45] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-15 18:19:45] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-15 18:19:45] (01) Save default settings
[2017-01-15 18:19:45] (01) NetworkName is pi_logger
[2017-01-15 18:19:45] (01) LogicalName is not set
[2017-01-15 18:19:45] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-15 18:19:45] (01) HTTP server is listening port 4444
[2017-01-15 18:19:45] (01) VXI-11 server is listening port 4445
[2017-01-15 18:19:53] (02) 01:19:53 Callback connected
[2017-01-16 04:34:27] (01) [1]ystream: 1428: yyPacketSetup error -8:"libusb_open:No such device (it may have been disconnected)" for METEOMK1-80051 index=0
[2017-01-16 04:34:27] (01) [1]ystream: 2089: retrying StartDevice...
[2017-01-16 04:34:27] (01) [1]ystream: 1428: yyPacketSetup error -8:"libusb_open:No such device (it may have been disconnected)" for METEOMK1-80051 index=0
[2017-01-16 04:34:27] (01) [1]ystream: 2089: retrying StartDevice...
[2017-01-16 04:34:27] (01) [1]ystream: 1428: yyPacketSetup error -8:"libusb_open:No such device (it may have been disconnected)" for METEOMK1-80051 index=0
[2017-01-16 04:34:27] (01) [1]ystream: 2089: retrying StartDevice...
[2017-01-16 04:34:27] (01) [1]ystream: 1428: yyPacketSetup error -8:"libusb_open:No such device (it may have been disconnected)" for METEOMK1-80051 index=0
[2017-01-16 04:34:27] (01) [1]ystream: 2089: retrying StartDevice...
[2017-01-16 04:34:28] (01) [1]ystream: 1259: drop 2 pkt on iface 0
[2017-01-16 04:34:28] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 04:34:50] (01) Send failed with error 32: Broken pipe
[2017-01-16 04:41:39] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-16 04:41:39] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-16 04:41:39] (01) Save default settings
[2017-01-16 04:41:39] (01) NetworkName is pi_logger
[2017-01-16 04:41:39] (01) LogicalName is not set
[2017-01-16 04:41:39] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 04:41:39] (01) HTTP server is listening port 4444
[2017-01-16 04:41:39] (01) VXI-11 server is listening port 4445
[2017-01-16 04:41:50] (02) 11:41:50 Callback connected
[2017-01-16 04:48:24] (02) 11:48:24 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 04:49:19] (02) 11:49:19 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 04:50:25] (01) Send failed with error 11: Resource temporarily unavailable
[2017-01-16 04:50:51] (01) Send failed with error 32: Broken pipe
[2017-01-16 11:45:23] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-16 11:45:23] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-16 11:45:23] (01) Save default settings
[2017-01-16 11:45:23] (01) NetworkName is pi_logger
[2017-01-16 11:45:23] (01) LogicalName is not set
[2017-01-16 11:45:23] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 11:45:23] (01) HTTP server is listening port 4444
[2017-01-16 11:45:23] (01) VXI-11 server is listening port 4445
[2017-01-16 11:45:31] (02) 18:45:31 Callback connected
[2017-01-16 11:46:05] (02) 18:46:05 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 11:47:12] (02) 18:47:12 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 11:57:33] (02) 18:57:33 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 12:04:05] (02) 19:04:05 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 12:07:00] (02) 19:07:00 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 12:34:30] (02) 19:34:30 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 13:38:43] (02) 20:38:43 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 13:47:07] (02) 20:47:07 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 13:47:40] (02) 20:47:40 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 13:47:52] (02) 20:47:52 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 13:48:15] (02) 20:48:15 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 14:14:09] (01) Send failed with error 32: Broken pipe
[2017-01-16 15:44:10] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-16 15:44:10] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-16 15:44:10] (01) Save default settings
[2017-01-16 15:44:10] (01) NetworkName is pi_logger
[2017-01-16 15:44:10] (01) LogicalName is not set
[2017-01-16 15:44:10] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 15:44:10] (01) HTTP server is listening port 4444
[2017-01-16 15:44:10] (01) VXI-11 server is listening port 4445
[2017-01-16 15:44:24] (02) 22:44:24 Callback connected
[2017-01-16 15:50:19] (01) Send failed with error 32: Broken pipe
[2017-01-16 20:16:21] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-16 20:16:21] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-16 20:16:21] (01) Save default settings
[2017-01-16 20:16:21] (01) NetworkName is pi_logger
[2017-01-16 20:16:21] (01) LogicalName is not set
[2017-01-16 20:16:21] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 20:16:21] (01) HTTP server is listening port 4444
[2017-01-16 20:16:21] (01) VXI-11 server is listening port 4445
[2017-01-16 20:16:29] (02) 03:16:29 Callback connected
[2017-01-16 20:23:56] (02) 03:23:56 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 20:26:11] (02) 03:26:11 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 20:30:14] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-16 20:30:14] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-16 20:30:14] (01) Save default settings
[2017-01-16 20:30:14] (01) NetworkName is pi_logger
[2017-01-16 20:30:14] (01) LogicalName is not set
[2017-01-16 20:30:14] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 20:30:14] (01) HTTP server is listening port 4444
[2017-01-16 20:30:14] (01) VXI-11 server is listening port 4445
[2017-01-16 20:30:25] (02) 03:30:25 Callback connected
[2017-01-16 20:34:31] (02) 03:34:31 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 20:35:04] (02) 03:35:04 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 20:42:16] (02) 03:42:16 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-16 20:45:22] (01) Send failed with error 32: Broken pipe
[2017-01-16 22:33:36] (02) 05:33:36 Callback: user abort [HTTP/1.0 500 Internal Server Err]
[2017-01-16 23:00:12] (01) Send failed with error 32: Broken pipe
[2017-01-16 23:30:45] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-16 23:30:45] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-16 23:30:45] (01) Save default settings
[2017-01-16 23:30:45] (01) NetworkName is pi_logger
[2017-01-16 23:30:45] (01) LogicalName is not set
[2017-01-16 23:30:45] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-16 23:30:45] (01) HTTP server is listening port 4444
[2017-01-16 23:30:45] (01) VXI-11 server is listening port 4445
[2017-01-16 23:30:59] (02) 06:30:59 Callback connected
[2017-01-16 23:53:46] (02) 06:53:46 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 00:07:13] (01) Send failed with error 32: Broken pipe
[2017-01-17 00:36:45] (01) Yoctopuce VirtualHub 1.10.26144 (dated Dec  5 2016)
[2017-01-17 00:36:45] (01) Serial is VIRTHUB0-32fbf2013b
[2017-01-17 00:36:45] (01) Save default settings
[2017-01-17 00:36:45] (01) NetworkName is pi_logger
[2017-01-17 00:36:45] (01) LogicalName is not set
[2017-01-17 00:36:45] (01) [1]ystream: 2198: Device METEOMK1-80051 plugged
[2017-01-17 00:36:45] (01) HTTP server is listening port 4444
[2017-01-17 00:36:45] (01) VXI-11 server is listening port 4445
[2017-01-17 00:36:59] (02) 07:36:59 Callback connected
[2017-01-17 00:51:18] (01) Send failed with error 11: Resource temporarily unavailable
[2017-01-17 00:51:26] (02) 07:51:26 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:09:16] (02) 08:09:16 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:20:45] (02) 08:20:45 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:21:17] (02) 08:21:17 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:21:30] (02) 08:21:30 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:21:42] (02) 08:21:42 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:43:22] (02) 08:43:22 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:43:47] (02) 08:43:47 Callback: bad reply header [HTTP/1.0 500 Internal Server Error]
[2017-01-17 01:44:29] (01) Send failed with error 32: Broken pipe
.

**Comment by yoctopuce** [comment]
Is it possible to have a remote access to your Raspberry PI? if yes could you contact support@yoctopuce.com
Alternatively could you send us the the configuration of your Apache Server.

**Comment by molly78** [comment]
Done :)

**Comment by yoctopuce** [comment]
It's in fact a bug in the VirtualHub. The bug has been fixed in the build 26443.
The VirtualHub can be downloaded here : http://www.yoctopuce.com/EN/virtualhub.php
